version: '3.4'
services:
  # Database
  db:
    container_name: db
    restart: unless-stopped
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=example
    volumes:
      - ./DB/initdb/:/docker-entrypoint-initdb.d
  phpmyadmin:
    container_name: st-pma
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=root
  go-app:
    container_name: wp-go
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
      context: .
    # get mariadb conatiner ip
    links:
      - db
    depends_on:
      - db
    environment:
    - DB_PASSWORD=root
    - DB_USER=root
    - DB_HOST=db
    - DB_NAME=example
    - DB_PORT:3306
    ports:
      - 8080:8080
    volumes:
      - ./internal:/go-app/internal
    # - db:/var/lib/mysql
  # dev-game:
  #   container_name: st-dev-game
  #   restart: unless-stopped
  #   build: .
  #   links:
  #     - db
  #   volumes:
  #     - ../:/slavictribes
  #   ports:
  #     - 8100:8100 # dev
  #     - 8101:8101 # alpha
  #     - 8103:8103 # beta
  #   entrypoint:
  #     - sh
  #     - -c
  #     - composer install > /dev/null 2>&1; php engine/bin/dev_serve.php
  #   depends_on:
  #     - db
  # dev-tools:
  #   container_name: st-dev-tools
  #   restart: unless-stopped
  #   build: .
  #   links:
  #     - db
  #   volumes:
  #     - ../:/slavictribes
  #   ports:
  #     - 8202:8202
  #   entrypoint:
  #     - sh
  #     - -c
  #     - composer install > /dev/null 2>&1; php engine/bin/dev_tools_serve.php
  # dev-www:
  #   container_name: st-dev-www
  #   restart: unless-stopped
  #   build: .
  #   links:
  #     - db
  #   volumes:
  #     - ../:/slavictribes
  #   ports:
  #     - 8203:8203
  #   entrypoint:
  #     - sh
  #     - -c
  #     - composer install > /dev/null 2>&1; php engine/bin/dev_www_serve.php